// ============================================
// INSIGHT INVESTIGATION API ROUTE
// Deep dive investigation into a specific insight
// Uses streaming to avoid CloudFront 30s timeout
// ============================================

import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { getRelevantInsights } from '@/lib/services/knowledge-base';
import { prisma } from '@/lib/prisma';

// Extend function timeout for investigation analysis
export const maxDuration = 120;

const anthropic = new Anthropic();

interface InvestigationRequest {
  insightId: string;
  insight: string;
  category: string;
  additionalContext?: string;
}

export async function POST(request: NextRequest) {
  // Parse & validate synchronously so we can still return 400.
  let body: InvestigationRequest;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { success: false, error: 'Invalid JSON body' },
      { status: 400 }
    );
  }

  const { insightId, insight, category, additionalContext } = body;

  if (!insight) {
    return NextResponse.json(
      { success: false, error: 'Insight text is required' },
      { status: 400 }
    );
  }

  // Use a TransformStream so we can write the SSE comment *immediately*
  // before doing any slow I/O.  The readable side is handed to the Response
  // and the writable side is consumed by our background async function.
  // This ensures CloudFront sees bytes well before its 30 s origin timeout,
  // even on a cold-start where Secrets Manager / Prisma init can take 10+ s.
  const encoder = new TextEncoder();
  const { readable, writable } = new TransformStream();
  const writer = writable.getWriter();

  // Fire-and-forget: all slow work runs in the background.
  (async () => {
    let fullText = '';

    try {
      // SSE comment — first byte for CloudFront, keeps connection alive.
      await writer.write(encoder.encode(': connected\n\n'));

      // Gather data in parallel
      const [relatedInsights, salesSummary, brandSummary] = await Promise.all([
        getRelevantInsights({ categories: [category], limit: 20 }),
        getSalesDataSummary(),
        getBrandDataSummary(),
      ]);

      const contextInsights = relatedInsights
        .filter(i => i.id !== insightId)
        .map(i => `- [${i.confidence}] ${i.insight}`)
        .join('\n');

      const systemPrompt = `You are a senior business analyst specializing in retail cannabis operations.
Your task is to conduct a deep investigation into a specific business insight that was generated by our Progressive Learning System.

The Progressive Learning System autonomously analyzes business data daily, correlates internal metrics with external market intelligence, and generates actionable insights. The insight you're investigating was identified through this automated analysis process.

You have access to:
1. The specific insight from the Progressive Learning System to investigate
2. Related insights from the Progressive Learning knowledge base
3. Current sales and brand performance data
4. Any additional context provided by the user

Your investigation should:
1. Validate whether the insight is still accurate based on current data
2. Identify root causes and contributing factors
3. Quantify the business impact where possible
4. Provide specific, actionable recommendations
5. Suggest metrics to track progress
6. Identify any risks or considerations

Format your response with clear sections using markdown headers.`;

      const userPrompt = `## Insight to Investigate (from Progressive Learning)
**Category:** ${category}
**Insight:** ${insight}

${additionalContext ? `## Additional Context from User\n${additionalContext}\n` : ''}

## Related Insights from Progressive Learning Knowledge Base
${contextInsights || 'No related insights available.'}

## Current Business Data

### Sales Summary
${salesSummary}

### Brand Performance
${brandSummary}

---

Please conduct a thorough investigation of this insight and provide:

1. **Validation Analysis** - Is this insight still accurate? What evidence supports or contradicts it?

2. **Root Cause Analysis** - What are the underlying factors driving this observation?

3. **Impact Assessment** - What is the estimated business impact? (revenue, margin, customer retention, etc.)

4. **Actionable Recommendations** - Provide 3-5 specific actions to take, prioritized by impact and effort

5. **Implementation Roadmap** - What should be done first, second, third?

6. **Success Metrics** - What KPIs should be tracked to measure progress?

7. **Risk Considerations** - What could go wrong? What dependencies exist?

8. **Follow-up Questions** - What additional data or analysis would help refine these recommendations?`;

      // Stream the Anthropic response
      const stream = anthropic.messages.stream({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 4096,
        system: systemPrompt,
        messages: [{ role: 'user', content: userPrompt }],
      });

      for await (const event of stream) {
        if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') {
          fullText += event.delta.text;
          await writer.write(encoder.encode(`data: ${JSON.stringify({ type: 'text', content: event.delta.text })}\n\n`));
        }
      }

      const finalMessage = await stream.finalMessage();
      const tokensUsed = finalMessage.usage.input_tokens + finalMessage.usage.output_tokens;

      const savedAnalysis = await prisma.analysisHistory.create({
        data: {
          analysisType: 'investigation',
          inputSummary: insight.slice(0, 500),
          outputSummary: fullText,
          insightsCount: 1,
          tokensUsed,
          model: 'claude-sonnet-4-20250514',
        },
      });

      await writer.write(encoder.encode(`data: ${JSON.stringify({
        type: 'done',
        investigationId: savedAnalysis.id,
        insightId,
        category,
        tokensUsed,
      })}\n\n`));

      await writer.close();
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Stream failed';
      console.error('Investigation stream error:', message);
      try {
        await writer.write(encoder.encode(`data: ${JSON.stringify({ type: 'error', error: message })}\n\n`));
        await writer.close();
      } catch {
        // writer may already be closed/errored
        writer.abort().catch(() => {});
      }
    }
  })();

  return new Response(readable, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
    },
  });
}

async function getSalesDataSummary(): Promise<string> {
  try {
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const salesData = await prisma.salesRecord.findMany({
      where: {
        date: { gte: thirtyDaysAgo },
      },
      select: {
        netSales: true,
        grossMarginPct: true,
        storeName: true,
        ticketsCount: true,
      },
      take: 1000,
    });

    if (salesData.length === 0) {
      return 'No recent sales data available.';
    }

    const totalRevenue = salesData.reduce((sum: number, s) => sum + Number(s.netSales || 0), 0);
    const avgMargin = salesData.reduce((sum: number, s) => sum + Number(s.grossMarginPct || 0), 0) / salesData.length;
    const totalTickets = salesData.reduce((sum: number, s) => sum + (s.ticketsCount || 0), 0);

    // Group by store
    const byStore = salesData.reduce((acc: Record<string, { revenue: number; count: number }>, s) => {
      const store = s.storeName || 'Unknown';
      if (!acc[store]) acc[store] = { revenue: 0, count: 0 };
      acc[store].revenue += Number(s.netSales || 0);
      acc[store].count += s.ticketsCount || 0;
      return acc;
    }, {});

    const storeBreakdown = Object.entries(byStore)
      .map(([store, data]) => `- ${store}: $${data.revenue.toLocaleString()} (${data.count} transactions)`)
      .join('\n');

    return `**Last 30 Days:**
- Total Revenue: $${totalRevenue.toLocaleString()}
- Average Margin: ${avgMargin.toFixed(1)}%
- Total Transactions: ${totalTickets.toLocaleString()}

**By Store:**
${storeBreakdown}`;
  } catch (error) {
    console.error('Error fetching sales summary:', error);
    return 'Unable to fetch sales data summary.';
  }
}

async function getBrandDataSummary(): Promise<string> {
  try {
    const brandData = await prisma.brandRecord.findMany({
      select: {
        originalBrandName: true,
        netSales: true,
        grossMarginPct: true,
      },
      orderBy: { netSales: 'desc' },
      take: 100,
    });

    if (brandData.length === 0) {
      return 'No brand data available.';
    }

    const topBrands = brandData
      .slice(0, 10)
      .map((b) => `- ${b.originalBrandName}: $${Number(b.netSales || 0).toLocaleString()} (${Number(b.grossMarginPct || 0).toFixed(1)}% margin)`)
      .join('\n');

    const lowMarginBrands = brandData
      .filter((b) => Number(b.grossMarginPct || 0) < 30 && Number(b.netSales || 0) > 1000)
      .slice(0, 5)
      .map((b) => `- ${b.originalBrandName}: ${Number(b.grossMarginPct || 0).toFixed(1)}% margin, $${Number(b.netSales || 0).toLocaleString()} sales`)
      .join('\n');

    return `**Top 10 Brands by Revenue:**
${topBrands}

**Low Margin Brands (< 30%):**
${lowMarginBrands || 'None identified'}`;
  } catch (error) {
    console.error('Error fetching brand summary:', error);
    return 'Unable to fetch brand data summary.';
  }
}
