// ============================================
// INSIGHT INVESTIGATION API ROUTE
// Deep dive investigation into a specific insight
// ============================================

import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { getRelevantInsights } from '@/lib/services/knowledge-base';
import { prisma } from '@/lib/prisma';

// Extend function timeout for investigation analysis
export const maxDuration = 120;

const anthropic = new Anthropic();

interface InvestigationRequest {
  insightId: string;
  insight: string;
  category: string;
  additionalContext?: string;
}

export async function POST(request: NextRequest) {
  try {
    const body: InvestigationRequest = await request.json();
    const { insightId, insight, category, additionalContext } = body;

    if (!insight) {
      return NextResponse.json(
        { success: false, error: 'Insight text is required' },
        { status: 400 }
      );
    }

    // Gather related insights for context
    const relatedInsights = await getRelevantInsights({
      categories: [category],
      limit: 20,
    });

    // Filter out the current insight being investigated
    const contextInsights = relatedInsights
      .filter(i => i.id !== insightId)
      .map(i => `- [${i.confidence}] ${i.insight}`)
      .join('\n');

    // Fetch recent sales data summary for context
    const salesSummary = await getSalesDataSummary();

    // Fetch brand data summary
    const brandSummary = await getBrandDataSummary();

    // Build the investigation prompt
    const systemPrompt = `You are a senior business analyst specializing in retail cannabis operations.
Your task is to conduct a deep investigation into a specific business insight that was generated by our Progressive Learning System.

The Progressive Learning System autonomously analyzes business data daily, correlates internal metrics with external market intelligence, and generates actionable insights. The insight you're investigating was identified through this automated analysis process.

You have access to:
1. The specific insight from the Progressive Learning System to investigate
2. Related insights from the Progressive Learning knowledge base
3. Current sales and brand performance data
4. Any additional context provided by the user

Your investigation should:
1. Validate whether the insight is still accurate based on current data
2. Identify root causes and contributing factors
3. Quantify the business impact where possible
4. Provide specific, actionable recommendations
5. Suggest metrics to track progress
6. Identify any risks or considerations

Format your response with clear sections using markdown headers.`;

    const userPrompt = `## Insight to Investigate (from Progressive Learning)
**Category:** ${category}
**Insight:** ${insight}

${additionalContext ? `## Additional Context from User\n${additionalContext}\n` : ''}

## Related Insights from Progressive Learning Knowledge Base
${contextInsights || 'No related insights available.'}

## Current Business Data

### Sales Summary
${salesSummary}

### Brand Performance
${brandSummary}

---

Please conduct a thorough investigation of this insight and provide:

1. **Validation Analysis** - Is this insight still accurate? What evidence supports or contradicts it?

2. **Root Cause Analysis** - What are the underlying factors driving this observation?

3. **Impact Assessment** - What is the estimated business impact? (revenue, margin, customer retention, etc.)

4. **Actionable Recommendations** - Provide 3-5 specific actions to take, prioritized by impact and effort

5. **Implementation Roadmap** - What should be done first, second, third?

6. **Success Metrics** - What KPIs should be tracked to measure progress?

7. **Risk Considerations** - What could go wrong? What dependencies exist?

8. **Follow-up Questions** - What additional data or analysis would help refine these recommendations?`;

    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      system: systemPrompt,
      messages: [
        {
          role: 'user',
          content: userPrompt,
        },
      ],
    });

    const analysisContent = response.content[0];
    if (analysisContent.type !== 'text') {
      throw new Error('Unexpected response type from Claude');
    }

    const tokensUsed = response.usage.input_tokens + response.usage.output_tokens;

    // Save investigation to AnalysisHistory for persistence
    const savedAnalysis = await prisma.analysisHistory.create({
      data: {
        analysisType: 'investigation',
        inputSummary: insight.slice(0, 500),
        outputSummary: analysisContent.text,
        insightsCount: 1,
        tokensUsed,
        model: 'claude-sonnet-4-20250514',
      },
    });

    return NextResponse.json({
      success: true,
      data: {
        investigation: analysisContent.text,
        investigationId: savedAnalysis.id,
        insightId,
        category,
        tokensUsed,
      },
    });
  } catch (error) {
    console.error('Error investigating insight:', error);
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : 'Failed to investigate insight' },
      { status: 500 }
    );
  }
}

async function getSalesDataSummary(): Promise<string> {
  try {
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const salesData = await prisma.salesRecord.findMany({
      where: {
        date: { gte: thirtyDaysAgo },
      },
      select: {
        netSales: true,
        grossMarginPct: true,
        storeName: true,
        ticketsCount: true,
      },
      take: 1000,
    });

    if (salesData.length === 0) {
      return 'No recent sales data available.';
    }

    const totalRevenue = salesData.reduce((sum: number, s) => sum + Number(s.netSales || 0), 0);
    const avgMargin = salesData.reduce((sum: number, s) => sum + Number(s.grossMarginPct || 0), 0) / salesData.length;
    const totalTickets = salesData.reduce((sum: number, s) => sum + (s.ticketsCount || 0), 0);

    // Group by store
    const byStore = salesData.reduce((acc: Record<string, { revenue: number; count: number }>, s) => {
      const store = s.storeName || 'Unknown';
      if (!acc[store]) acc[store] = { revenue: 0, count: 0 };
      acc[store].revenue += Number(s.netSales || 0);
      acc[store].count += s.ticketsCount || 0;
      return acc;
    }, {});

    const storeBreakdown = Object.entries(byStore)
      .map(([store, data]) => `- ${store}: $${data.revenue.toLocaleString()} (${data.count} transactions)`)
      .join('\n');

    return `**Last 30 Days:**
- Total Revenue: $${totalRevenue.toLocaleString()}
- Average Margin: ${avgMargin.toFixed(1)}%
- Total Transactions: ${totalTickets.toLocaleString()}

**By Store:**
${storeBreakdown}`;
  } catch (error) {
    console.error('Error fetching sales summary:', error);
    return 'Unable to fetch sales data summary.';
  }
}

async function getBrandDataSummary(): Promise<string> {
  try {
    const brandData = await prisma.brandRecord.findMany({
      select: {
        originalBrandName: true,
        netSales: true,
        grossMarginPct: true,
      },
      orderBy: { netSales: 'desc' },
      take: 100,
    });

    if (brandData.length === 0) {
      return 'No brand data available.';
    }

    const topBrands = brandData
      .slice(0, 10)
      .map((b) => `- ${b.originalBrandName}: $${Number(b.netSales || 0).toLocaleString()} (${Number(b.grossMarginPct || 0).toFixed(1)}% margin)`)
      .join('\n');

    const lowMarginBrands = brandData
      .filter((b) => Number(b.grossMarginPct || 0) < 30 && Number(b.netSales || 0) > 1000)
      .slice(0, 5)
      .map((b) => `- ${b.originalBrandName}: ${Number(b.grossMarginPct || 0).toFixed(1)}% margin, $${Number(b.netSales || 0).toLocaleString()} sales`)
      .join('\n');

    return `**Top 10 Brands by Revenue:**
${topBrands}

**Low Margin Brands (< 30%):**
${lowMarginBrands || 'None identified'}`;
  } catch (error) {
    console.error('Error fetching brand summary:', error);
    return 'Unable to fetch brand data summary.';
  }
}
