export interface EventVenue {
  id: number;
  name: string;
  lat: number;
  lng: number;
  category: 'cultural' | 'festival' | 'theater' | 'convention' | 'sports' | 'music';
  color: string;
  events: { name: string; date: string; time?: string }[];
  radius: number;
}

export const CATEGORY_LABELS: Record<string, string> = {
  theater: 'Theater & Performance',
  festival: 'Festival & Arts',
  convention: 'Convention & Conference',
  sports: 'Sports & Entertainment',
  cultural: 'Cultural Events',
  music: 'Music & Nightlife',
};

export const CATEGORY_COLORS: Record<string, string> = {
  cultural: '#f38181',
  festival: '#4ecdc4',
  convention: '#ffe66d',
  sports: '#95e1d3',
  theater: '#ff6b6b',
  music: '#aa96da',
};

export const DEMO_EVENT_VENUES: EventVenue[] = [
  {
    id: 1,
    name: 'Chinatown',
    lat: 37.7941,
    lng: -122.4078,
    category: 'cultural',
    color: '#f38181',
    events: [
      { name: 'Chinese New Year Parade', date: 'Feb 15, 2026' },
      { name: 'Flower Market Fair', date: 'Feb 14-15, 2026' },
    ],
    radius: 400,
  },
  {
    id: 2,
    name: 'Second Street (Downtown First Thursdays)',
    lat: 37.7879,
    lng: -122.399,
    category: 'festival',
    color: '#4ecdc4',
    events: [{ name: 'Downtown First Thursdays', date: 'Feb 5, 2026', time: '5-10 PM' }],
    radius: 200,
  },
  {
    id: 3,
    name: "Levi's Stadium",
    lat: 37.4033,
    lng: -121.9695,
    category: 'sports',
    color: '#95e1d3',
    events: [{ name: 'Super Bowl LX', date: 'Feb 8, 2026' }],
    radius: 500,
  },
  {
    id: 4,
    name: 'Orpheum Theatre',
    lat: 37.7793,
    lng: -122.4107,
    category: 'theater',
    color: '#ff6b6b',
    events: [
      { name: 'The Notebook, The Musical', date: 'Feb 10 - Mar 1, 2026' },
      { name: 'The Book of Mormon', date: 'Throughout Feb 2026' },
    ],
    radius: 150,
  },
  {
    id: 5,
    name: 'San Francisco Playhouse',
    lat: 37.7873,
    lng: -122.4053,
    category: 'theater',
    color: '#ff6b6b',
    events: [{ name: 'M. Butterfly', date: 'Feb 5 - Mar 14, 2026' }],
    radius: 150,
  },
  {
    id: 6,
    name: 'Castro Theatre',
    lat: 37.7621,
    lng: -122.435,
    category: 'music',
    color: '#aa96da',
    events: [{ name: 'Sam Smith: To Be Free Residency', date: 'Feb 2026' }],
    radius: 150,
  },
  {
    id: 7,
    name: 'Union Square',
    lat: 37.7879,
    lng: -122.4074,
    category: 'cultural',
    color: '#f38181',
    events: [
      { name: 'Weekly Free Activities', date: 'Every week' },
      { name: 'Cultural Saturdays', date: 'Every 2nd Saturday' },
    ],
    radius: 200,
  },
  {
    id: 8,
    name: 'Exploratorium',
    lat: 37.8017,
    lng: -122.3975,
    category: 'cultural',
    color: '#f38181',
    events: [{ name: 'After Dark Thursday Nights', date: 'Every Thursday', time: '6 PM' }],
    radius: 200,
  },
  {
    id: 9,
    name: 'Hyatt Regency SF (Embarcadero)',
    lat: 37.7943,
    lng: -122.396,
    category: 'convention',
    color: '#ffe66d',
    events: [{ name: 'SF Writers Conference', date: 'Feb 12-15, 2026' }],
    radius: 200,
  },
  {
    id: 10,
    name: 'Hyatt Regency Downtown SOMA',
    lat: 37.7853,
    lng: -122.3966,
    category: 'convention',
    color: '#ffe66d',
    events: [{ name: 'SF 61st Out of Town Show', date: 'Feb 20, 2026', time: '6 PM' }],
    radius: 200,
  },
  {
    id: 11,
    name: 'Moscone Center',
    lat: 37.784,
    lng: -122.401,
    category: 'convention',
    color: '#ffe66d',
    events: [{ name: 'Various Tech & Industry Conferences', date: 'Throughout Feb 2026' }],
    radius: 300,
  },
  {
    id: 12,
    name: 'Chase Center',
    lat: 37.768,
    lng: -122.3877,
    category: 'sports',
    color: '#95e1d3',
    events: [
      { name: 'Golden State Warriors Games', date: 'Throughout Feb 2026' },
      { name: 'USF vs Gonzaga Basketball', date: 'Feb 18, 2026' },
    ],
    radius: 300,
  },
  {
    id: 13,
    name: 'War Memorial Opera House',
    lat: 37.7788,
    lng: -122.4203,
    category: 'theater',
    color: '#ff6b6b',
    events: [{ name: 'SF Ballet Performances', date: 'Throughout Feb 2026' }],
    radius: 200,
  },
  {
    id: 14,
    name: 'Davies Symphony Hall',
    lat: 37.7775,
    lng: -122.42,
    category: 'music',
    color: '#aa96da',
    events: [{ name: 'SF Symphony Concerts', date: 'Throughout Feb 2026' }],
    radius: 200,
  },
  {
    id: 15,
    name: 'Punch Line Comedy Club',
    lat: 37.7945,
    lng: -122.4005,
    category: 'music',
    color: '#aa96da',
    events: [
      { name: 'SF Sketchfest Shows', date: 'Through Feb 1, 2026' },
      { name: 'Stand-up Comedy', date: 'Throughout Feb 2026' },
    ],
    radius: 100,
  },
  {
    id: 16,
    name: "Cobb's Comedy Club",
    lat: 37.8057,
    lng: -122.4218,
    category: 'music',
    color: '#aa96da',
    events: [
      { name: 'SF Sketchfest Shows', date: 'Through Feb 1, 2026' },
      { name: 'Stand-up Comedy', date: 'Throughout Feb 2026' },
    ],
    radius: 100,
  },
  {
    id: 17,
    name: 'Roxie Theater',
    lat: 37.7614,
    lng: -122.4181,
    category: 'festival',
    color: '#4ecdc4',
    events: [
      { name: 'SF Indie Fest', date: 'Feb 5-15, 2026' },
      { name: 'Mostly British Film Festival', date: 'Feb 5-12, 2026' },
    ],
    radius: 150,
  },
  {
    id: 18,
    name: 'Various SOMA Venues (Noise Pop)',
    lat: 37.7785,
    lng: -122.4056,
    category: 'festival',
    color: '#4ecdc4',
    events: [{ name: 'Noise Pop Festival', date: 'Feb 19 - Mar 7, 2026' }],
    radius: 400,
  },
  {
    id: 19,
    name: "Fisherman's Wharf / Pier 39",
    lat: 37.8087,
    lng: -122.4098,
    category: 'cultural',
    color: '#f38181',
    events: [
      { name: 'Bay Cruises', date: 'Daily' },
      { name: 'Blue & Gold Fleet Tours', date: 'Daily' },
    ],
    radius: 300,
  },
  {
    id: 20,
    name: 'Golden Gate Park',
    lat: 37.7694,
    lng: -122.4862,
    category: 'sports',
    color: '#95e1d3',
    events: [{ name: 'SF Half Marathon', date: 'Feb 1, 2026' }],
    radius: 500,
  },
  {
    id: 21,
    name: 'Folsom Street (SOMA)',
    lat: 37.7783,
    lng: -122.4075,
    category: 'festival',
    color: '#4ecdc4',
    events: [{ name: 'SOMA Nights Monthly Festival', date: 'Monthly' }],
    radius: 300,
  },
  {
    id: 22,
    name: 'Outer Sunset',
    lat: 37.7534,
    lng: -122.505,
    category: 'cultural',
    color: '#f38181',
    events: [{ name: 'Sunset Night Market', date: 'Feb 27, 2026', time: '5-10 PM' }],
    radius: 300,
  },
];
