/**
 * Example SEO audit data for the demo experience.
 * Two audits: one for each demo store's website.
 */

export interface DemoSeoAudit {
  id: string;
  domain: string;
  status: string;
  createdAt: string;
  completedAt: string;
  summary: {
    healthScore: number;
    totalPages: number;
    totalIssues: number;
    criticalIssues: number;
    highIssues: number;
    mediumIssues: number;
    lowIssues: number;
  };
  pages: Array<{
    url: string;
    statusCode: number;
    title: string;
    issues: Array<{
      id: string;
      code: string;
      category: string;
      priority: string;
      title: string;
      description: string;
      recommendation: string;
    }>;
  }>;
}

export const EXAMPLE_SEO_AUDITS: DemoSeoAudit[] = [
  {
    id: 'demo-seo-001',
    domain: 'https://greenleafmarket.com',
    status: 'completed',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 2 * 86400000 + 300000).toISOString(),
    summary: {
      healthScore: 74,
      totalPages: 32,
      totalIssues: 27,
      criticalIssues: 3,
      highIssues: 6,
      mediumIssues: 11,
      lowIssues: 7,
    },
    pages: [
      {
        url: 'https://greenleafmarket.com/',
        statusCode: 200,
        title: 'Greenleaf Market - Premium Cannabis Dispensary Downtown',
        issues: [
          {
            id: 'seo-gl-1',
            code: 'META_DESC_LENGTH',
            category: 'SEO',
            priority: 'high',
            title: 'Meta description too long',
            description: 'Meta description is 185 characters. Search engines typically display 150-160 characters.',
            recommendation: 'Shorten the meta description to 150-160 characters while keeping primary keywords.',
          },
          {
            id: 'seo-gl-2',
            code: 'LCP_SLOW',
            category: 'Performance',
            priority: 'critical',
            title: 'Largest Contentful Paint above 4 seconds',
            description: 'LCP measured at 4.2s on mobile. Google recommends under 2.5s for good user experience.',
            recommendation: 'Optimize hero image (currently 2.8MB). Convert to WebP format and add lazy loading for below-fold images.',
          },
          {
            id: 'seo-gl-3',
            code: 'HSTS_MISSING',
            category: 'Security',
            priority: 'medium',
            title: 'HTTP Strict Transport Security header missing',
            description: 'The site does not send an HSTS header, leaving users vulnerable to protocol downgrade attacks.',
            recommendation: 'Add Strict-Transport-Security header with a max-age of at least 31536000 (1 year).',
          },
        ],
      },
      {
        url: 'https://greenleafmarket.com/menu',
        statusCode: 200,
        title: 'Our Menu | Greenleaf Market',
        issues: [
          {
            id: 'seo-gl-4',
            code: 'IMG_ALT_MISSING',
            category: 'Accessibility',
            priority: 'high',
            title: '12 images missing alt text',
            description: 'Product images on the menu page lack alt attributes, impacting accessibility and image search rankings.',
            recommendation: 'Add descriptive alt text to all product images (e.g., "Pacific Bloom Hybrid Flower 3.5g").',
          },
          {
            id: 'seo-gl-5',
            code: 'H1_MISSING',
            category: 'SEO',
            priority: 'medium',
            title: 'No H1 heading found',
            description: 'The menu page lacks a proper H1 heading tag, which helps search engines understand page content.',
            recommendation: 'Add an H1 heading such as "Cannabis Menu - Flower, Edibles, Vapes & More".',
          },
          {
            id: 'seo-gl-6',
            code: 'MOBILE_TAP_TARGET',
            category: 'Mobile',
            priority: 'medium',
            title: 'Tap targets too small on mobile',
            description: '8 clickable elements are smaller than 48x48px, making them difficult to tap on mobile devices.',
            recommendation: 'Increase the size of buttons and links to at least 48x48px with adequate spacing between them.',
          },
          {
            id: 'seo-gl-7',
            code: 'RENDER_BLOCKING',
            category: 'Performance',
            priority: 'high',
            title: '3 render-blocking resources detected',
            description: 'External CSS and JS files block initial page render, adding 1.2s to First Contentful Paint.',
            recommendation: 'Inline critical CSS, defer non-essential JS, and use async loading for third-party scripts.',
          },
        ],
      },
      {
        url: 'https://greenleafmarket.com/about',
        statusCode: 200,
        title: 'About Us | Greenleaf Market',
        issues: [
          {
            id: 'seo-gl-8',
            code: 'THIN_CONTENT',
            category: 'Content',
            priority: 'medium',
            title: 'Thin content detected',
            description: 'Page has only 87 words of content. Pages with less than 300 words may be seen as low-quality by search engines.',
            recommendation: 'Expand the about page with your story, team, mission, and community involvement (aim for 500+ words).',
          },
          {
            id: 'seo-gl-9',
            code: 'BROKEN_LINK_INTERNAL',
            category: 'Links',
            priority: 'high',
            title: '2 broken internal links found',
            description: 'Links to /team and /history return 404 errors.',
            recommendation: 'Remove or update the broken links. Create the missing pages or redirect to the appropriate content.',
          },
        ],
      },
      {
        url: 'https://greenleafmarket.com/deals',
        statusCode: 200,
        title: 'Daily Deals | Greenleaf Market',
        issues: [
          {
            id: 'seo-gl-10',
            code: 'CLS_HIGH',
            category: 'Performance',
            priority: 'critical',
            title: 'Cumulative Layout Shift above 0.25',
            description: 'CLS measured at 0.34. Elements shift during page load, creating a poor user experience.',
            recommendation: 'Add explicit width and height to promotional banner images and use CSS aspect-ratio for dynamic content areas.',
          },
          {
            id: 'seo-gl-11',
            code: 'CANONICAL_MISSING',
            category: 'SEO',
            priority: 'medium',
            title: 'Missing canonical tag',
            description: 'No canonical URL specified. This can cause duplicate content issues if the page is accessible via multiple URLs.',
            recommendation: 'Add a canonical link tag pointing to the preferred URL.',
          },
          {
            id: 'seo-gl-12',
            code: 'LOW_TEXT_RATIO',
            category: 'Content',
            priority: 'low',
            title: 'Low text-to-HTML ratio',
            description: 'Text-to-HTML ratio is 8%. A ratio below 10% may indicate the page has too little visible text content.',
            recommendation: 'Add more descriptive text content to the page. Include deal descriptions and category information.',
          },
        ],
      },
      {
        url: 'https://greenleafmarket.com/contact',
        statusCode: 200,
        title: 'Contact Us | Greenleaf Market',
        issues: [
          {
            id: 'seo-gl-13',
            code: 'FORM_LABEL_MISSING',
            category: 'Accessibility',
            priority: 'medium',
            title: '3 form fields missing labels',
            description: 'Input fields in the contact form lack associated <label> elements, making the form difficult for screen readers.',
            recommendation: 'Add <label> elements with for attributes matching each input id, or use aria-label attributes.',
          },
          {
            id: 'seo-gl-14',
            code: 'STRUCTURED_DATA_MISSING',
            category: 'SEO',
            priority: 'low',
            title: 'No LocalBusiness schema found',
            description: 'The contact page lacks LocalBusiness structured data with address, phone, and hours.',
            recommendation: 'Add LocalBusiness Schema.org markup with NAP (Name, Address, Phone) and operating hours.',
          },
        ],
      },
      {
        url: 'https://greenleafmarket.com/blog',
        statusCode: 200,
        title: 'Cannabis Blog | Greenleaf Market',
        issues: [
          {
            id: 'seo-gl-15',
            code: 'DUPLICATE_META',
            category: 'SEO',
            priority: 'medium',
            title: 'Duplicate meta descriptions on blog posts',
            description: '4 blog posts share the same generic meta description.',
            recommendation: 'Write unique meta descriptions for each blog post that summarize the specific content.',
          },
          {
            id: 'seo-gl-16',
            code: 'LINK_NOFOLLOW_EXCESSIVE',
            category: 'Links',
            priority: 'low',
            title: 'Excessive nofollow on internal links',
            description: '6 internal links use rel="nofollow" unnecessarily, preventing PageRank flow.',
            recommendation: 'Remove nofollow from internal links unless specifically required for UGC or sponsored content.',
          },
          {
            id: 'seo-gl-17',
            code: 'IMG_LARGE_UNCOMPRESSED',
            category: 'Performance',
            priority: 'high',
            title: '5 blog images exceed 500KB',
            description: 'Uncompressed blog images total 4.8MB on the listing page.',
            recommendation: 'Compress images to under 200KB each. Use WebP format with responsive srcset for different screen sizes.',
          },
        ],
      },
      {
        url: 'https://greenleafmarket.com/loyalty',
        statusCode: 200,
        title: 'Loyalty Program | Greenleaf Market',
        issues: [],
      },
      {
        url: 'https://greenleafmarket.com/locations',
        statusCode: 200,
        title: 'Store Locations | Greenleaf Market',
        issues: [
          {
            id: 'seo-gl-18',
            code: 'MIXED_CONTENT',
            category: 'Security',
            priority: 'critical',
            title: 'Mixed content detected on map embed',
            description: 'The embedded Google Map is loaded over HTTP instead of HTTPS, triggering browser security warnings.',
            recommendation: 'Update the map embed URL to use HTTPS protocol.',
          },
          {
            id: 'seo-gl-19',
            code: 'VIEWPORT_NOT_SET',
            category: 'Mobile',
            priority: 'low',
            title: 'Map container not responsive',
            description: 'The map iframe uses a fixed width of 600px, causing horizontal scrolling on mobile devices.',
            recommendation: 'Set the map container to width: 100% with a responsive aspect ratio wrapper.',
          },
        ],
      },
      {
        url: 'https://greenleafmarket.com/faq',
        statusCode: 200,
        title: 'FAQ | Greenleaf Market',
        issues: [],
      },
      {
        url: 'https://greenleafmarket.com/careers',
        statusCode: 200,
        title: 'Careers | Greenleaf Market',
        issues: [
          {
            id: 'seo-gl-20',
            code: 'OG_TAGS_MISSING',
            category: 'SEO',
            priority: 'low',
            title: 'Open Graph tags missing',
            description: 'No Open Graph meta tags found. Shared links on social media will display generic previews.',
            recommendation: 'Add og:title, og:description, og:image, and og:url meta tags for better social sharing.',
          },
          {
            id: 'seo-gl-21',
            code: 'COLOR_CONTRAST',
            category: 'Accessibility',
            priority: 'medium',
            title: 'Insufficient color contrast on 4 elements',
            description: 'Light gray text on white background fails WCAG AA contrast requirements (ratio 3.2:1, minimum 4.5:1).',
            recommendation: 'Darken the text color to achieve at least a 4.5:1 contrast ratio against the background.',
          },
          {
            id: 'seo-gl-22',
            code: 'STALE_CONTENT',
            category: 'Content',
            priority: 'low',
            title: 'Content appears outdated',
            description: 'Job listings reference dates from over 6 months ago. Stale content can reduce trust signals.',
            recommendation: 'Update or remove expired job listings. Add a "last updated" timestamp to the page.',
          },
        ],
      },
    ],
  },
  {
    id: 'demo-seo-002',
    domain: 'https://emeraldcollective.com',
    status: 'completed',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 4 * 86400000 + 420000).toISOString(),
    summary: {
      healthScore: 61,
      totalPages: 28,
      totalIssues: 31,
      criticalIssues: 5,
      highIssues: 8,
      mediumIssues: 12,
      lowIssues: 6,
    },
    pages: [
      {
        url: 'https://emeraldcollective.com/',
        statusCode: 200,
        title: 'Emerald Collective | Midtown Cannabis Dispensary',
        issues: [
          {
            id: 'seo-ec-1',
            code: 'RENDER_BLOCKING',
            category: 'Performance',
            priority: 'critical',
            title: '4 render-blocking resources detected',
            description: 'External CSS and JavaScript files block initial page render, adding 1.8s to First Contentful Paint.',
            recommendation: 'Inline critical CSS, defer non-essential JS, and use async loading for third-party scripts.',
          },
          {
            id: 'seo-ec-2',
            code: 'MOBILE_VIEWPORT',
            category: 'Mobile',
            priority: 'high',
            title: 'Viewport not configured for mobile',
            description: 'The page does not use a responsive viewport meta tag, causing poor display on mobile devices.',
            recommendation: 'Add <meta name="viewport" content="width=device-width, initial-scale=1"> to the head.',
          },
          {
            id: 'seo-ec-3',
            code: 'TLS_OUTDATED',
            category: 'Security',
            priority: 'critical',
            title: 'TLS 1.0/1.1 still supported',
            description: 'Server accepts connections using deprecated TLS 1.0 and 1.1 protocols, which have known vulnerabilities.',
            recommendation: 'Disable TLS 1.0 and 1.1 on the server. Only allow TLS 1.2 and 1.3 connections.',
          },
          {
            id: 'seo-ec-4',
            code: 'H1_MULTIPLE',
            category: 'SEO',
            priority: 'medium',
            title: 'Multiple H1 tags found',
            description: 'Page contains 3 H1 elements. Best practice is to have a single H1 that describes the page topic.',
            recommendation: 'Reduce to a single H1 tag and use H2-H6 for subheadings.',
          },
        ],
      },
      {
        url: 'https://emeraldcollective.com/products',
        statusCode: 200,
        title: 'Products - Emerald Collective',
        issues: [
          {
            id: 'seo-ec-5',
            code: 'STRUCTURED_DATA_MISSING',
            category: 'SEO',
            priority: 'high',
            title: 'No structured data found',
            description: 'No Schema.org markup detected. Structured data helps search engines display rich results.',
            recommendation: 'Add LocalBusiness and Product schema markup to improve search appearance.',
          },
          {
            id: 'seo-ec-6',
            code: 'DUPLICATE_TITLE',
            category: 'SEO',
            priority: 'medium',
            title: 'Duplicate title tag',
            description: 'This page shares the same title with 3 other pages on the site.',
            recommendation: 'Create unique, descriptive title tags for each page (include product category in title).',
          },
          {
            id: 'seo-ec-7',
            code: 'IMG_SIZE_LARGE',
            category: 'Performance',
            priority: 'high',
            title: '8 images exceed 500KB',
            description: 'Large unoptimized images slow page load significantly. Total image weight: 12.4MB.',
            recommendation: 'Compress images, use WebP format, and implement responsive image srcset.',
          },
          {
            id: 'seo-ec-8',
            code: 'ARIA_INVALID',
            category: 'Accessibility',
            priority: 'high',
            title: '5 invalid ARIA attributes detected',
            description: 'Incorrect aria-role and aria-label usage on product filter controls.',
            recommendation: 'Fix ARIA attributes: use role instead of aria-role, and ensure aria-label values are descriptive.',
          },
          {
            id: 'seo-ec-9',
            code: 'LAZY_LOAD_ATF',
            category: 'Performance',
            priority: 'medium',
            title: 'Above-the-fold images use lazy loading',
            description: 'Hero and featured product images are set to loading="lazy", delaying their display.',
            recommendation: 'Remove lazy loading from above-the-fold images. Only lazy-load images that appear below the initial viewport.',
          },
        ],
      },
      {
        url: 'https://emeraldcollective.com/contact',
        statusCode: 200,
        title: 'Contact | Emerald Collective',
        issues: [
          {
            id: 'seo-ec-10',
            code: 'HTTPS_MIXED',
            category: 'Security',
            priority: 'critical',
            title: 'Mixed content detected',
            description: 'The page loads 3 resources over HTTP instead of HTTPS, triggering browser security warnings.',
            recommendation: 'Update all resource URLs to use HTTPS. Check embedded maps, fonts, and tracking scripts.',
          },
          {
            id: 'seo-ec-11',
            code: 'FORM_NO_CSRF',
            category: 'Security',
            priority: 'high',
            title: 'Contact form lacks CSRF protection',
            description: 'The contact form does not include a CSRF token, making it vulnerable to cross-site request forgery.',
            recommendation: 'Implement CSRF token validation on the contact form submission endpoint.',
          },
          {
            id: 'seo-ec-12',
            code: 'HEADING_ORDER',
            category: 'Accessibility',
            priority: 'medium',
            title: 'Heading hierarchy skips levels',
            description: 'Page jumps from H1 directly to H4, skipping H2 and H3 levels.',
            recommendation: 'Use headings in sequential order (H1, H2, H3) without skipping levels.',
          },
        ],
      },
      {
        url: 'https://emeraldcollective.com/about',
        statusCode: 200,
        title: 'About | Emerald Collective',
        issues: [
          {
            id: 'seo-ec-13',
            code: 'THIN_CONTENT',
            category: 'Content',
            priority: 'medium',
            title: 'Thin content detected',
            description: 'Page contains only 142 words. Pages below 300 words may be flagged as low-quality.',
            recommendation: 'Expand the about page to at least 500 words. Include company history, team bios, and mission statement.',
          },
          {
            id: 'seo-ec-14',
            code: 'IMG_ALT_MISSING',
            category: 'Accessibility',
            priority: 'high',
            title: '6 images missing alt text',
            description: 'Team photos and decorative images lack alt attributes.',
            recommendation: 'Add descriptive alt text to team photos. Use empty alt="" for purely decorative images.',
          },
          {
            id: 'seo-ec-15',
            code: 'BROKEN_EXTERNAL_LINK',
            category: 'Links',
            priority: 'medium',
            title: '3 broken external links',
            description: 'Links to partner websites return 404 or timeout errors.',
            recommendation: 'Remove or update broken external links. Consider adding a link monitoring process.',
          },
        ],
      },
      {
        url: 'https://emeraldcollective.com/events',
        statusCode: 200,
        title: 'Events | Emerald Collective',
        issues: [
          {
            id: 'seo-ec-16',
            code: 'FID_HIGH',
            category: 'Performance',
            priority: 'critical',
            title: 'First Input Delay above 300ms',
            description: 'FID measured at 420ms due to heavy JavaScript execution during page load.',
            recommendation: 'Break up long JavaScript tasks, defer non-critical scripts, and use web workers for heavy computation.',
          },
          {
            id: 'seo-ec-17',
            code: 'STALE_CONTENT',
            category: 'Content',
            priority: 'medium',
            title: 'Past events still displayed prominently',
            description: '5 events from 3+ months ago are listed above upcoming events.',
            recommendation: 'Archive or move past events below upcoming ones. Add structured event data with dates.',
          },
          {
            id: 'seo-ec-18',
            code: 'MOBILE_FONT_SIZE',
            category: 'Mobile',
            priority: 'medium',
            title: 'Font too small on mobile',
            description: 'Body text is 11px on mobile screens. Minimum recommended size is 16px.',
            recommendation: 'Set base font size to at least 16px on mobile. Use relative units (rem) for scalability.',
          },
          {
            id: 'seo-ec-19',
            code: 'OG_IMAGE_MISSING',
            category: 'SEO',
            priority: 'low',
            title: 'Open Graph image missing',
            description: 'No og:image meta tag found. Social shares will show a generic placeholder.',
            recommendation: 'Add an og:image tag with a compelling event-related image (1200x630px recommended).',
          },
        ],
      },
      {
        url: 'https://emeraldcollective.com/blog',
        statusCode: 200,
        title: 'Blog | Emerald Collective',
        issues: [
          {
            id: 'seo-ec-20',
            code: 'KEYWORD_STUFFING',
            category: 'Content',
            priority: 'high',
            title: 'Potential keyword stuffing detected',
            description: 'The keyword "dispensary" appears 23 times on a single page (density 8.4%), which may trigger search engine penalties.',
            recommendation: 'Reduce keyword density to 1-2%. Use natural language and semantic variations instead.',
          },
          {
            id: 'seo-ec-21',
            code: 'CANONICAL_SELF',
            category: 'SEO',
            priority: 'low',
            title: 'Self-referencing canonical on paginated pages',
            description: 'Paginated blog pages (page 2, 3) point to themselves instead of the canonical first page.',
            recommendation: 'Set canonical tags on paginated pages to point to the main blog URL, or use rel="prev/next" pagination.',
          },
          {
            id: 'seo-ec-22',
            code: 'REDIRECT_CHAIN',
            category: 'Links',
            priority: 'medium',
            title: '2 redirect chains detected',
            description: 'Two blog post URLs go through 3+ redirects before reaching the final page, wasting crawl budget.',
            recommendation: 'Update internal links to point directly to the final destination URL. Eliminate intermediate redirects.',
          },
        ],
      },
      {
        url: 'https://emeraldcollective.com/loyalty-signup',
        statusCode: 200,
        title: 'Join Our Loyalty Program | Emerald Collective',
        issues: [],
      },
      {
        url: 'https://emeraldcollective.com/order-online',
        statusCode: 200,
        title: 'Order Online | Emerald Collective',
        issues: [
          {
            id: 'seo-ec-23',
            code: 'CLS_HIGH',
            category: 'Performance',
            priority: 'critical',
            title: 'Cumulative Layout Shift above 0.25',
            description: 'CLS measured at 0.42 due to dynamically loaded product cards without reserved space.',
            recommendation: 'Reserve layout space for dynamic content with min-height or aspect-ratio. Use skeleton loading states.',
          },
          {
            id: 'seo-ec-24',
            code: 'META_TITLE_LENGTH',
            category: 'SEO',
            priority: 'low',
            title: 'Title tag too long',
            description: 'Title is 72 characters. Search engines typically display 50-60 characters.',
            recommendation: 'Shorten the title to under 60 characters while keeping the primary keyword near the beginning.',
          },
          {
            id: 'seo-ec-25',
            code: 'TOUCH_TARGET_OVERLAP',
            category: 'Mobile',
            priority: 'high',
            title: 'Overlapping touch targets',
            description: 'Add-to-cart buttons overlap with quantity selectors on mobile, causing incorrect taps.',
            recommendation: 'Add at least 8px spacing between interactive elements and ensure minimum 48x48px touch targets.',
          },
          {
            id: 'seo-ec-26',
            code: 'MISSING_SKIP_LINK',
            category: 'Accessibility',
            priority: 'low',
            title: 'No skip-to-content link',
            description: 'Page lacks a skip navigation link, forcing keyboard users to tab through the entire header.',
            recommendation: 'Add a visually hidden "Skip to main content" link as the first focusable element on the page.',
          },
          {
            id: 'seo-ec-27',
            code: 'CONTENT_DUPLICATE',
            category: 'Content',
            priority: 'medium',
            title: 'Duplicate content with products page',
            description: '68% of content on this page matches the /products page, creating a duplicate content concern.',
            recommendation: 'Differentiate the order page with unique content, CTAs, and product presentation. Use canonical tags if needed.',
          },
          {
            id: 'seo-ec-28',
            code: 'BROKEN_LINK_INTERNAL',
            category: 'Links',
            priority: 'high',
            title: '4 broken internal links',
            description: 'Links to product detail pages return 404 errors for discontinued items.',
            recommendation: 'Redirect discontinued product URLs to the main products page or relevant category.',
          },
        ],
      },
    ],
  },
];
